instances:
  - name: "technitium_main"
    port: 8041
    bot_token: "123456:ABC-DEF"
    chat_id: "-456789123"
    allowed_ips:
      # - "0.0.0.0/0"
      # - "172.0.0.0/16"
      - "192.168.225.0/24"
      - "192.168.226.3/32"
    retry_count: 3
    retry_delay: 2

  - name: "backup_dns"
    port: 8042
    bot_token: "789101:GHI-JKL"
    chat_id: "-987654321"
    allowed_ips:
      # - "0.0.0.0/0"
      # - "172.0.0.0/16"
      - "192.168.225.0/24"
      - "192.168.226.3/32"
    retry_count: 5
    retry_delay: 5
